# Generated by Django 2.2.2 on 2019-06-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('full_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('L', 'Land'), ('C', 'Creature'), ('A', 'Artifact'), ('E', 'Enchantment'), ('S', 'Sorcery'), ('I', 'Instant'), ('P', 'Planeswalker')], max_length=1)),
                ('type_line', models.CharField(max_length=20)),
                ('cmc', models.IntegerField()),
                ('mana_cost', models.CharField(blank=True, max_length=15)),
                ('power', models.IntegerField(blank=True)),
                ('toughness', models.IntegerField(blank=True)),
                ('loyalty', models.IntegerField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=255)),
                ('oracle_text', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Artist')),
                ('colors', models.ManyToManyField(to='cards.Color')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Edition')),
            ],
            options={
                'ordering': ['edition', 'number'],
                'unique_together': {('number', 'edition')},
            },
        ),
    ]
