# Generated by Django 2.2.2 on 2019-06-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190611_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
    ]
