# Generated by Django 2.2.2 on 2019-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('Standard', 'Standard'), ('Modern', 'Modern'), ('Legacy', 'Legacy'), ('Pauper', 'Pauper'), ('Vintage', 'Vintage'), ('EDH', 'EDH')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='formats',
            field=models.ManyToManyField(to='cards.Format'),
        ),
    ]
