# Generated by Django 2.2.2 on 2019-06-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190611_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='cards.Color'),
        ),
    ]
