# Generated by Django 2.2.2 on 2019-06-11 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0006_auto_20190611_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('JA', 'Japanese'), ('KO', 'Korean'), ('RU', 'Russian'), ('CH', 'Chinese')], max_length=2)),
                ('state', models.CharField(choices=[('NM', 'Nearly Mint'), ('EX', 'Excellent'), ('LP', 'Lightly Played'), ('PL', 'Played')], max_length=2)),
                ('commentary', models.CharField(blank=True, max_length=255, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='instances',
            field=models.ManyToManyField(blank=True, through='cards.CardInstance', to=settings.AUTH_USER_MODEL),
        ),
    ]
