# Generated by Django 2.2.2 on 2019-06-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20190611_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Modern', 'Modern'), ('Legacy', 'Legacy'), ('Pauper', 'Pauper'), ('Vintage', 'Vintage'), ('Commander', 'Commander')], max_length=10, unique=True),
        ),
    ]
