# Generated by Django 2.2.2 on 2019-06-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20190612_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('M', 'Mythic')], max_length=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Artist'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Rarity'),
            preserve_default=False,
        ),
    ]
